name: Update Files

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "fonts/**"
      - "LittlePaimon/**"

jobs:
  update:
    name: Update Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx pydantic tqdm

      - name: Update Star Rail Resources
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python update_starrail_res.py

      - name: Update files
        run: |
          python generate_res_list.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: ":wrench: 自动更新资源列表"
          add: .

      - uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: Resources-V1.0
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: Resources-V1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Resources
        uses: softprops/action-gh-release@v2
        if: ${{  success() }}
        with:
          tag_name: Resources-V1.0
          append_body: true
          files: |
            resources.zip
            star_rail.zip
