name: Update Star Rail Resources

on:
  workflow_dispatch:

jobs:
  update:
    name: Update Star Rail Resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx pydantic tqdm

      - name: Update Star Rail Resources
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python update_starrail_res.py

      - name: Update Files
        run: |
          python generate_res_list.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: ":wrench: 自动更新星铁资源"
          add: .
